// Generated by scripts/generate-pwa-build.mjs. Do not edit.
export const CURRENT_BUILD = {
  buildId: "89312a2da52811d9a8e574ef392b32bd",
  builtAt: "2026-07-28T18:35:50.000Z",
} as const;
export const CURRENT_BUILD_ID = CURRENT_BUILD.buildId;
